name: "learn-github-actions"
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
          
      - name: install dependencies
        run:  |
              gem install bundler
              bundle install --jobs 4 --retry 3
        
      - name: Run tests
        run: bundle exec rspec

    
